config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  get 'countries', to: 'pages#countries'

  # animals index will return a view; countries index will return a json
  resources :animals, only: :index
  # resources :countries, only: :index

  namespace :api do
    namespace :v1 do
     resources :countries, only: [:index]
    end
  end

end

app/models/animal.rb
class Animal < ApplicationRecord

  def self.find_by_name(arg)
    where('name LIKE ?', "%#{arg}%")
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord

  def self.find_by_name(arg)
    where('name LIKE ?', "%#{arg}%")
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index

    if params[:name]

      @animals = Animal.find_by_name(params[:name])

    else
      @animals = Animal.all
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:name)
  end
end

app/controllers/api/v1/countries_controller.rb
class Api::V1::CountriesController < ApplicationController
  # protect_from_forgery with: :null_session

  def index
    # abort params.inspect

    if params[:name]
      # abort params[:name].inspect
      @countries = Country.find_by_name(params[:name])

    else
      @countries = Country.all
    end

    render json: @countries
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session

end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    # abort params.inspect
    @countries = Country.all
    abort @countries.length.inspect
    render json: @countries

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

  def countries
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/api/v1/countries_helper.rb
module Api::V1::CountriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/animals/index.html.haml
%h1 Animals INDEX: Rails view
=link_to 'Home', root_path
%br
%br
=link_to 'All Animals', animals_path
%br
%br

=form_tag("/animals", method: "get") do
  =label_tag(:name, "Search by name: ")
  =text_field_tag(:name)
  =submit_tag("Go")


-unless @animals.empty?
  %ul
  - @animals.each do |a|
    %li=a.name
- else
  %b No match

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SearchFormsRailsReact
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pages/countries.html.haml
%h1 Countries INDEX: React Component


= react_component 'Countries'

app/views/pages/home.html.haml
%h1 HOME

=link_to 'Go to Animals', animals_path

=link_to 'Go to Countries', countries_path